Bump trietools gomod to rc 1.4.0
ElrondNetwork/elrond-tools-go pull request #42
Opened 2022-10-20 13:05 UTC by BeniaminDrasovean

2022-10-20 13:46 UTC, raduchis approved these changes

2022-10-20 13:46 UTC, raduchis commented on trieTools/accountStorageExporter/main.go
> +	err = common.GetErrorFromChanNonBlocking(iteratorChannels.ErrChan)
:+1:

2022-10-20 13:46 UTC, raduchis commented on trieTools/go.mod
> -replace github.com/ElrondNetwork/arwen-wasm-vm/v1_2 v1.2.40 => github.com/ElrondNetwork/arwen-wasm-vm v1.2.40
not needed any more?

2022-10-20 14:46 UTC, raduchis requested changes

2022-10-20 14:46 UTC, raduchis commented on trieTools/trieToolsCommon/common.go
> +	args := pruning.StorerArgs{
the NewPersistersTracker is missing; could be added like this:

`epochsData := pruning.EpochArgs{
		NumOfEpochsToKeep:     uint32(maxDBValue) + 1,
		NumOfActivePersisters: uint32(maxDBValue) + 1,
		StartingEpoch:         uint32(maxDBValue),
	}

	args := pruning.StorerArgs{
		Identifier:                "",
		ShardCoordinator:          testscommon.NewMultiShardsCoordinatorMock(1),
		CacheConf:                 cacheConfig,
		PathManager:               components.NewSimplePathManager(dbPath),
		DbPath:                    "",
		PersisterFactory:          factory.NewPersisterFactory(localDbConfig),
		Notifier:                  notifier.NewManualEpochStartNotifier(),
		OldDataCleanerProvider:    &testscommon.OldDataCleanerProviderStub{},
		CustomDatabaseRemover:     disabled.NewDisabledCustomDatabaseRemover(),
		MaxBatchSize:              45000,
		EpochsData:                epochsData,
		PruningEnabled:            true,
		EnabledDbLookupExtensions: false,
		PersistersTracker:         pruning.NewPersistersTracker(epochsData),
	}`

2022-10-24 08:22 UTC, BeniaminDrasovean commented on trieTools/trieToolsCommon/common.go
> +func CreateStorageManager(storer storage.Storer) (common.StorageManager, error) {
Added.

2022-10-24 08:31 UTC, BeniaminDrasovean commented on trieTools/trieChecker/main.go
> +	iteratorChannels := &common.TrieIteratorChannels{
Done.

2022-10-24 08:35 UTC, iulianpascalau approved these changes

2022-10-24 08:38 UTC, raduchis approved these changes

2022-10-24 08:41 UTC, merged